win_all:
	g++ -Wall -pedantic cplaylist_test.cpp ../../lib/cplaylist.o  -o ../../bin/cplaylist_test.exe
	
linux_all:
	g++ -Wall -pedantic cplaylist_test.cpp ../../lib/cplaylist_linux.o  -o ../../bin/cplaylist_test