language: cpp

before_install:
    # For gcc-6
    - sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 1397BC53640DB551
    - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test

    # For Qt 5.7
    - sudo add-apt-repository --yes ppa:beineri/opt-qt57-trusty
    - sudo apt-get install -qq g++-6 qt57-meta-full

script:
    - QT_ENV_SCRIPT=$(find /opt -name 'qt*-env.sh')
    - source $QT_ENV_SCRIPT
    - qmake
    - ./makeall
