win_all:
	g++ -Wall -pedantic caudiotags_test.cpp ../../lib/caudiotags.o  -o ../../bin/caudiotags_test.exe
	
linux_all:
	g++ -Wall -pedantic caudiotags_test.cpp -D_NIX ../../lib/caudiotags_linux.o  -o ../../bin/caudiotags_test