#!/bin/sh

echo "--- Building MUI ---\n"

# cfmod
echo "--- Building component cfmod ---\n"
cd ./src/cfmod
make linux_lib

if [ $? -ne 0 ]
then
	echo  "--- Error building cfmod ---\n"
	exit
fi

echo "--- Component cfmod built ---\n"

# cplaylist
echo  "--- Building component cplaylist ---\n"
cd ../cplaylist
make linux_lib

if [ $? -ne 0 ]
then
	echo  "--- Error building cplaylist ---\n"
	exit
fi

echo  "--- Component cplaylist built ---\n"

# caudiotags
echo  "--- Building component caudiotags ---\n"
cd ../caudiotags
make linux_lib

if [ $? -ne 0 ]
then
	echo  "--- Error building caudiotags ---\n"
	exit
fi

echo  "--- Component caudiotags built ---\n"

# MUI
echo  "--- Building MUI ---\n"
cd ../MUI
qmake
make

if [ $? -ne 0 ]
then
	echo " --- Error building MUI --- \n"
	exit
fi

echo "--- MUI Built ---\n"
cd ../../
